#!/usr/bin/env python3
"""Extract the TIOS bitmap fonts from an AMS OS image into a C table.

The fonts the game draws with (DrawStr/DrawChar/GrayDrawStrExt2B) are ROM data
and are not part of the Super Mario 68K source drop, so they are lifted from an
AMS image instead. Offsets below were located by structure, not by symbol:

  6x8   0x0bac3a  the only 2048-byte run (256 chars x 8 rows) in the image whose
                  bytes all have their low 2 bits clear - the signature of a
                  6-pixel-wide glyph stored left-aligned in a byte.
  8x10  0x9e506   found by correlating per-character ink counts against the
                  confirmed 6x8 table, then verified by rendering text.

Both were checked by rendering "Mario68" and reading it back.

Usage: mkfont.py <AMS image> > compat/font_data.c
"""
import sys

OFFSETS = {"6x8": (0x0BAC3A, 8), "8x10": (0x09E506, 10)}
PROBE = b"Mario68"


def glyph(d, base, h, ch):
    return d[base + ch * h: base + ch * h + h]


def legible(d, base, h):
    """Cheap sanity check: space blank, probe characters all inked."""
    if any(glyph(d, base, h, 0x20)):
        return False
    return all(any(glyph(d, base, h, c)) for c in PROBE)


def main():
    d = open(sys.argv[1], "rb").read()
    print("// Generated by tools/mkfont.py - do not edit.")
    print("// TIOS bitmap fonts extracted from an AMS OS image; see that script")
    print("// for how the offsets were located and verified.")
    print('#include "font_data.h"\n')
    for name, (base, h) in OFFSETS.items():
        if not legible(d, base, h):
            sys.exit("font %s at 0x%06x failed the sanity check" % (name, base))
        ident = "Font" + name.replace("x", "x")
        print("const unsigned char %s[256][%d] = {" % (ident, h))
        for c in range(256):
            row = ", ".join("0x%02X" % b for b in glyph(d, base, h, c))
            print("\t{ %s }," % row)
        print("};\n")


if __name__ == "__main__":
    main()
