#!/usr/bin/env python3
"""Extract the TIOS bitmap fonts from an AMS OS image into a C table.

The fonts the game draws with (DrawStr/DrawChar/GrayDrawStrExt2B) are ROM data
and are not part of the Super Mario 68K source drop, so they are lifted from an
AMS image instead. Offsets below were located by structure, not by symbol:

  6x8   0x0bac3a  the only 2048-byte run (256 chars x 8 rows) in the image whose
                  bytes all have their low 2 bits clear - the signature of a
                  6-pixel-wide glyph stored left-aligned in a byte.
  8x10  0x9e506   found by correlating per-character ink counts against the
                  confirmed 6x8 table, then verified by rendering text.
  4x6   0x0f9f5e  same ink-count correlation at a 6-byte stride (0.84 against
                  the 6x8 table, next candidate 0.59). It is not a plain
                  bitmap run like the other two, which is why the low-bits scan
                  never found it: the 4x6 face is *proportional*, so each
                  character is a 6-byte record of one advance byte followed by
                  five glyph rows. The split was pinned by the advance byte
                  equalling ink width + 1 for all 94 printable ASCII codes at
                  this alignment (41/94 and 43/94 one record either way).

All three were checked by rendering "Mario68" and reading it back.

The 4x6 rows are stored with the leftmost pixel in bit 6, not bit 7, so this
script shifts them up one to match the other two faces. Only char 0x00 - the
checkerboard cursor block, which is not text - has anything in bit 7 to lose.

Usage: mkfont.py <AMS image> > compat/font_data.c
"""
import sys

FIXED = {"6x8": (0x0BAC3A, 8), "8x10": (0x09E506, 10)}
PROP4x6 = 0x0F9F5E
PROBE = b"Mario68"


def glyph(d, base, h, ch):
    return d[base + ch * h: base + ch * h + h]


def legible(d, base, h):
    """Cheap sanity check: space blank, probe characters all inked."""
    if any(glyph(d, base, h, 0x20)):
        return False
    return all(any(glyph(d, base, h, c)) for c in PROBE)


def rec4x6(d, ch):
    """(advance, five rows) for one character of the proportional 4x6 face."""
    r = d[PROP4x6 + ch * 6: PROP4x6 + ch * 6 + 6]
    return r[0], [(b << 1) & 0xFF for b in r[1:]]


def check4x6(d):
    """Advance must be ink width + 1 across printable ASCII, and space blank."""
    adv, rows = rec4x6(d, 0x20)
    if any(rows) or adv < 1:
        return False
    for c in range(0x21, 0x7F):
        adv, rows = rec4x6(d, c)
        ink = 0
        for b in rows:
            ink |= b
        if not ink:
            return False
        width = 8 - ((ink & -ink).bit_length() - 1)
        if adv != width + 1:
            return False
    return True


def table(ident, h, rows):
    print("const unsigned char %s[256][%d] = {" % (ident, h))
    for r in rows:
        print("\t{ %s }," % ", ".join("0x%02X" % b for b in r))
    print("};\n")


def main():
    d = open(sys.argv[1], "rb").read()
    print("// Generated by tools/mkfont.py - do not edit.")
    print("// TIOS bitmap fonts extracted from an AMS OS image; see that script")
    print("// for how the offsets were located and verified.")
    print('#include "font_data.h"\n')

    for name, (base, h) in FIXED.items():
        if not legible(d, base, h):
            sys.exit("font %s at 0x%06x failed the sanity check" % (name, base))
        table("Font" + name, h, [glyph(d, base, h, c) for c in range(256)])

    if not check4x6(d):
        sys.exit("font 4x6 at 0x%06x failed the sanity check" % PROP4x6)
    # Sixth row is the cell's blank line-gap row; the ROM stores only the five
    # inked ones, but carrying it keeps the array shape honest to the name.
    table("Font4x6", 6, [rec4x6(d, c)[1] + [0x00] for c in range(256)])
    print("const unsigned char Font4x6Width[256] = {")
    for c in range(0, 256, 16):
        print("\t%s" % " ".join("%d," % rec4x6(d, i)[0] for i in range(c, c + 16)))
    print("};")


if __name__ == "__main__":
    main()
